# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Shelley
email: james@jshelley.uk

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>James Shelley blog</h1><h3>A place for my random posts.!</h3>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesshelley.github.io" # the base hostname & protocol for your site
twitter_username: jamesshelley_
github_username:  jamesshelley

# Build settings
markdown: kramdown
